---
- name: 'Install and configure caddy'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.caddy_server'
      caddy_config: |
        http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:80
        respond /* 200 {
            body "Hello vagrant-libvirt setup!
        "
            close
        }
